version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/pension-management-portal:5"
        LoadBalancerInfo:
          ContainerName: "pension-management-portal"
          ContainerPort: "80"

        PlatformVersion: "LATEST"